---
# ==========================================
# PHASE 1: System Prep & Docker Installation
# ==========================================
- name: Prepare Pis and Install Docker
  hosts: managers
  become: yes

  pre_tasks:
    - name: Initialize system
      include_role:
        name: system_init

  roles:
    - role: docker_installation
    - role: docker_swarm_init
    - role: akasha_cloud