---
# roles/system_update/tasks/main.yml

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  become: yes
#
#- name: Ensure UFW is installed
#  apt:
#    name: ufw
#    state: present
#
#- name: Ensure port 8080 is allowed in UFW
#  community.general.ufw:
#    rule: allow
#    port: '8080'
#    proto: tcp
#    state: enabled
