all:
  children:
    akasha:
      children:
        managers:
          hosts:
            node01:
              ansible_host: akasha
              ansible_user: lysz210
              ansible_become_user: root
