---
- name: Check if node is already part of a swarm
  become: yes
  ansible.builtin.command: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
  register: swarm_state
  changed_when: false

- name: Initialize Docker Swarm on the manager
  become: yes
  ansible.builtin.command: docker swarm init
  when: swarm_state.stdout != "active"
  register: swarm_init

- name: Get swarm join tokens
  become: yes
  ansible.builtin.command: docker swarm join-token -q {{ item }}
  loop:
    - manager
    - worker
  register: join_tokens
  when: swarm_state.stdout != "active" or swarm_init.changed

- name: Store tokens as facts
  ansible.builtin.set_fact:
    manager_token: "{{ join_tokens.results[0].stdout }}"
    worker_token: "{{ join_tokens.results[1].stdout }}"
  when: swarm_state.stdout != "active" or swarm_init.changed

- name: Create shared overlay network for Akasha Cloud
  community.docker.docker_network:
    name: "{{ shared_net_name }}"
    driver: overlay
    attachable: true