---

- name: Create directory for stack
  ansible.builtin.file:
    path: "{{ akasha_cloud_stack_directory }}"
    state: directory
    mode: '0755'

- name: Create Traefik config and cert folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ akasha_cloud_stack_directory }}/certs"
    - "{{ akasha_cloud_stack_directory }}/dynamic"

- name: Generate OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ akasha_cloud_stack_directory }}/certs/local.key"
    size: 2048
    mode: '0600'

- name: Generate OpenSSL CSR
  community.crypto.openssl_csr:
    path: "{{ akasha_cloud_stack_directory }}/certs/local.csr"
    privatekey_path: "{{ akasha_cloud_stack_directory }}/certs/local.key"
    common_name: "akasha.local"
    subject_alt_name:
      - "DNS:akasha.local"
      - "DNS:*.akasha.local"

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ akasha_cloud_stack_directory }}/certs/local.crt"
    privatekey_path: "{{ akasha_cloud_stack_directory }}/certs/local.key"
    csr_path: "{{ akasha_cloud_stack_directory }}/certs/local.csr"
    provider: selfsigned
    selfsigned_not_after: "+365d"
    mode: '0644'

- name: Deploy dynamic TLS configuration file
  ansible.builtin.copy:
    dest: "{{ akasha_cloud_stack_directory }}/dynamic/tls.yaml"
    mode: '0644'
    content: |
      tls:
        certificates:
          - certFile: /certs/local.crt
            keyFile: /certs/local.key

- name: Deploy compose template
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ akasha_cloud_stack_directory }}/compose.yaml"
    mode: '0644'

- name: Deploy Swarm stack
  community.docker.docker_stack:
    state: present
    name: akasha_stack
    compose: "{{ akasha_cloud_stack_directory }}/compose.yaml"
    prune: true