ansible_connection: ssh
ansible_become_method: sudo
ansible_ssh_pass: "{{ vault_ssh_password }}"
ansible_become_pass: "{{ vault_ssh_password }}"

ansible_become_flags: '-tt'

# The master network name for Akasha_cloud
public_net_name: akasha_net
private_nats_net_name: capacnan_net

capacnan_blueprint_url: http://capacnan-configs:8000/blueprint.yaml