---

- name: Create directory for stack
  ansible.builtin.file:
    path: "{{ claviger_stack_directory }}"
    state: directory
    mode: '0755'

- name: Deploy .env template from Vault vars
  ansible.builtin.template:
    src: env.j2
    dest: "{{ claviger_stack_directory }}/.env"
    mode: '0600'

- name: Deploy compose template
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ claviger_stack_directory }}/compose.yaml"
    mode: '0644'

- name: Deploy Swarm stack
  community.docker.docker_stack:
    state: present
    name: claviger_stack
    compose:
      - "{{ claviger_stack_directory }}/compose.yaml"
    prune: true
    resolve_image: always